---
name: WaterFurnace Aurora
version: "1.2.2"
slug: waterfurnace_aurora
description: WaterFurnace Aurora MQTT Bridge for Home Assistant
url: https://github.com/atheismann/home-assistant-aurora-ruby-addon
arch:
  - aarch64
  - amd64
init: false
hassio_api: true
auth_api: true
options:
  connection_type: serial
  serial_port: /dev/ttyUSB0
  network_host: ""
  network_port: 2000
  network_protocol: tcp
  mqtt_host: core-mosquitto
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  mqtt_ssl: false
  web_aid_tool_port: 0
  log_level: info
schema:
  connection_type: list(serial|network)
  serial_port: str
  network_host: str?
  network_port: port?
  network_protocol: list(tcp|telnet)?
  mqtt_host: str
  mqtt_port: port
  mqtt_username: str?
  mqtt_password: password?
  mqtt_ssl: bool
  web_aid_tool_port: int(0,65535)?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
devices:
  - /dev/ttyUSB0
  - /dev/ttyUSB1
  - /dev/ttyAMA0
  - /dev/ttyACM0
  - /dev/serial0
uart: true
services:
  - mqtt:need
