version: "3"

services:
  addon:
    build:
      context: .
      dockerfile: Dockerfile
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    privileged: true
    environment:
      - SERIAL_PORT=/dev/ttyUSB0
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
